disabled_rules:
  - computed_accessors_order
  - identifier_name
  - line_length
  - trailing_whitespace

analyzer_rules:
  - explicit_self
  - unused_control_flow_label
  - unused_import

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - for_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - reduce_boolean
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded:
  - HomeSample
  - HomeTests
  - HomeSampleUITests
  - CoreTests
  - ProfileTests
  - UITests

file_length:
  warning: 600
  error: 1200

closure_body_length:
  warning: 50
  error: 100

type_name:
  allowed_symbols: "`"

custom_rules:
  vertical_whitespace_opening_braces:
    included: '.*.swift'
    regex: '[{(\[][ \t]*\n[ \t]*\n'
    name: 'Vertical Whitespace after Opening Braces'
    message: "Don't include vertical whitespace (empty line) after opening braces."
    severity: warning
  vertical_whitespace_closing_braces:
    included: '.*.swift'
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: 'Vertical Whitespace before Closing Braces'
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
