default_platform(:ios)

platform :ios do
  desc "Run tests on simulator"
  lane :test do
    scan(
      scheme: "Similarity",
      devices: ["iPhone 8"], # Altere para o simulador desejado
      clean: true,
      workspace: "Similarity.xcworkspace",
      destination: "platform=iOS Simulator,name=iPhone 8,OS=latest"
    )
  end
end
