name: Similarity
options:
  bundleIdPrefix: "com.jonatanortiz"
  deploymentTarget:
    iOS: '16.4'
  createIntermediateGroups: true
configs:
  Debug: debug
  Homolog: release
  Release: release
configFiles:
  Debug: Configs/BaseDebug.xcconfig
  Homolog: Configs/BaseHomolog.xcconfig
  Release: Configs/BaseRelease.xcconfig
settings:
  SWIFT_VERSION: 5.0
targets:
  Similarity:
    type: application
    platform: iOS
    configFiles:
      Debug: Configs/AppDebug.xcconfig
      Homolog: Configs/AppHomolog.xcconfig
      Release: Configs/AppRelease.xcconfig
    sources:
      - path: Similarity
    dependencies:
      - target: Core/Core
      - framework: Core.framework
        implicit: true
      - target: CoreInterface/CoreInterface
      - framework: CoreInterface.framework
        implicit: true
      - target: Home/Home
      - framework: Home.framework
        implicit: true
      - target: Profile/Profile
      - framework: Profile.framework
        implicit: true
      - target: UI/UI
      - framework: UI.framework
        implicit: true
    preBuildScripts:
      - path: ${SWIFTGEN_SH_PATH}
        name: SwiftGen
        basedOnDependencyAnalysis: false
      - path: ${SWIFTLINT_SH_PATH}
        name: SwiftLint
        basedOnDependencyAnalysis: false
  SimilarityTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      SWIFT_VERSION: ${IOS_TESTS_SWIFT_VERSION}
      IPHONEOS_DEPLOYMENT_TARGET: ${IOS_TESTS_DEPLOY_TARGET}
    configFiles:
      Debug: Configs/TestsDebug.xcconfig
      Homolog: Configs/TestsHomolog.xcconfig
      Release: Configs/TestsRelease.xcconfig
    sources: [SimilarityTests]
projectReferences:
  Core:
    path: ../Modules/Features/Core/Core.xcodeproj
  CoreInterface:
    path: ../Modules/Features/CoreInterface/CoreInterface.xcodeproj
  Home:
    path: ../Modules/Features/Home/Home.xcodeproj
  Profile:
    path: ../Modules/Features/Profile/Profile.xcodeproj
  UI:
    path: ../Modules/Features/UI/UI.xcodeproj
schemes:
  Similarity - Dev:
    build:
      targets:
        Similarity: all
        SimilarityTests: [test]
    run:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: SimilarityTests
          randomExecutionOrder: true
  All Tests:
    build:
      targets:
        Similarity: all
        SimilarityTests: [test]
    run:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets: [Similarity, Home/Home]
      targets:
        - name: SimilarityTests
          parallelizable: ${IOS_TESTS_PARALLELIZABLE}
          randomExecutionOrder: true
        - name: Home/HomeTests
          parallelizable: ${IOS_TESTS_PARALLELIZABLE}
          randomExecutionOrder: true
  Similarity - Homolog:
    build:
      targets:
        Similarity: all
    run:
      config: Homolog
    profile:
      config: Homolog
    analyze:
      config: Homolog
    archive:
      config: Homolog
    test:
      config: Homolog
      gatherCoverageData: true
      targets:
        - name: SimilarityTests
          randomExecutionOrder: true
  Similarity - Prod:
    build:
      targets:
        Similarity: all
    run:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
    test:
      config: Release
      gatherCoverageData: true
      targets:
        - name: SimilarityTests
          randomExecutionOrder: true